import { Check, ExternalLink, Lightbulb, ShieldCheck } from "lucide-react";
import { annualSalary, fieldValue, salaryLabel, type JourneyProfile } from "@/lib/journey-profile";
import { euEeaCountries, mvpRules, officialSources } from "@/lib/mvp-visa-rules";

export function ContractInsights({ profile, compact = false }: { profile: JourneyProfile; compact?: boolean }) {
  const salary = annualSalary(profile);
  const eur = fieldValue(profile.employment.currency) === "EUR";
  const nationality = fieldValue(profile.qualification.nationality);
  const free = Object.hasOwn(euEeaCountries, nationality) || nationality === "CH";
  const standard = salary !== null && eur && salary >= mvpRules.standardBlueCardAnnualEur;
  const reduced = salary !== null && eur && salary >= mvpRules.reducedBlueCardAnnualEur;
  const known = (key: keyof JourneyProfile["employment"]) => fieldValue(profile.employment[key]);
  return <aside className="contract-insights" aria-label="Recommendations and insights">
    <div className="insights-heading"><Lightbulb size={22} /><h2>Recommendations & Insights</h2></div>
    <section className="panel insight-card visa-insight"><span className="pill blue"><ShieldCheck size={14} /> Visa readiness</span><h3>{free ? "Free-movement pathway" : "Potential EU Blue Card route"}</h3><strong className="insight-salary">{salaryLabel(profile)}</strong>
      <p>{free ? "Your confirmed EU/EEA or Swiss nationality points to a free-movement pathway. The Blue Card salary check is not needed for this nationality." : !profile.contractReviewed || salary === null || !eur ? "Confirm your contract and gross pay in EUR to see how your salary compares. No visa eligibility is assumed." : standard ? "Salary threshold met; qualification/job matching still needs verification." : reduced ? "Your salary reaches the reduced reference, but the qualifying category and additional conditions need separate verification." : "Your salary is below these 2026 Blue Card references. Explore other potential routes and verify your circumstances."}</p>
      {!free && <><dl className="threshold-list"><div><dt>2026 general threshold</dt><dd>€50,700</dd></div><div><dt>2026 reduced reference</dt><dd>€45,934.20</dd></div></dl>{compact ? <details className="insight-conditions"><summary>How these thresholds apply</summary><p className="small-note">The reduced reference may apply to qualifying shortage occupations or graduates whose last degree was obtained within three years, subject to further conditions and Federal Employment Agency approval. This MVP evaluates the standard academic case; it does not decide reduced-case eligibility.</p><p className="small-note">Salary alone is insufficient. Qualification comparability, job match, contract duration and other admission conditions still matter. Verify current rules for applications outside 2026.</p><a className="text-link" href={officialSources.blueCard.url} target="_blank" rel="noreferrer">Official Blue Card guidance <ExternalLink size={13} /></a></details> : <><p className="small-note">The reduced reference may apply to qualifying shortage occupations or graduates whose last degree was obtained within three years, subject to further conditions and Federal Employment Agency approval. This MVP evaluates the standard academic case; it does not decide reduced-case eligibility.</p><p className="small-note">Salary alone is insufficient. Qualification comparability, job match, contract duration and other admission conditions still matter. Verify current rules for applications outside 2026.</p><a className="text-link" href={officialSources.blueCard.url} target="_blank" rel="noreferrer">Official Blue Card guidance <ExternalLink size={13} /></a></>}</>}
    </section>
    <details className="panel insight-card working-benefits" open={compact ? undefined : true}><summary>Key German Working Benefits</summary>
      <div className="benefit-insight"><h4><Check size={15} /> Vacation / Urlaub</h4><p>{known("annualLeave") ? `Your contract records ${known("annualLeave")} working days a year. ` : "Your vacation allowance is not yet confirmed. "}The statutory minimum is 20 days for a standard five-day week, or 24 for a six-day week. Employers may offer more; entitlement can depend on time worked and individual circumstances.</p><a className="text-link" href={officialSources.vacation.url} target="_blank" rel="noreferrer">Federal Leave Act <ExternalLink size={12} /></a></div>
      <div className="benefit-insight"><h4>Bildungsurlaub / Bildungszeit</h4><p>Paid education leave is available in many federal states. Entitlement, approved courses and notice requirements depend on the state. Check the rules for your workplace{known("workLocation") ? ` in ${known("workLocation")}` : ""}.</p><a className="text-link" href={officialSources.educationLeave.url} target="_blank" rel="noreferrer">Berlin example · other states differ <ExternalLink size={12} /></a></div>
      <div className="benefit-insight"><h4>Probezeit / probation</h4><p>{known("probationPeriod") ? `Your recorded probation period: ${known("probationPeriod")}.` : "Your probation period is not confirmed."} This is an agreed introductory period. Six months is common, but is not universally mandatory.</p></div>
      <div className="benefit-insight"><h4>Notice period</h4><p>{known("noticePeriod") || "No notice period confirmed yet. Check the contract wording and any referenced agreement."}</p><a className="text-link" href={officialSources.notice.url} target="_blank" rel="noreferrer">Statutory notice rules and exceptions <ExternalLink size={12} /></a></div>
    </details>
  </aside>;
}
